### ISSUE TITLE
Intermittent RSTcheckBear 35s timeout

### ISSUE THREAD

**Issue by jayvdb** [coala/docker-coala-base#98]
See https://travis-ci.org/jayvdb/docker-coala-base/builds/202889527 and https://travis-ci.org/jayvdb/docker-coala-base/builds/202614783

```
E           Traceback (most recent call last):
E             File "/coala/coalib/bears/Bear.py", line 250, in execute
E               result = self.run_bear_from_section(args, kwargs)
E             File "/coala/coalib/bears/Bear.py", line 243, in run_bear_from_section
E               return self.run(*args, **kwargs)
E             File "/coala/coalib/bearlib/abstractions/Linter.py", line 555, in run
E               cwd=self.get_config_dir())
E             File "/coala/coalib/misc/Shell.py", line 142, in run_shell_command
E               ret = p.communicate(stdin)
E             File "/usr/lib64/python3.5/subprocess.py", line 1068, in communicate
E               stdout, stderr = self._communicate(input, endtime, timeout)
E             File "/usr/lib64/python3.5/subprocess.py", line 1702, in _communicate
E               ready = selector.select(timeout)
E             File "/usr/lib64/python3.5/selectors.py", line 367, in select
E               fd_event_list = self._poll.poll(timeout)
E             File "/usr/lib/python3.5/site-packages/pytest_timeout.py", line 110, in handler
E               timeout_sigalrm(item, timeout)
E             File "/usr/lib/python3.5/site-packages/pytest_timeout.py", line 243, in timeout_sigalrm
E               pytest.fail('Timeout >%ss' % timeout)
E             File "/usr/lib/python3.5/site-packages/_pytest/runner.py", line 542, in fail
E               raise Failed(msg=msg, pytrace=pytrace)
E           Failed: Timeout >35.0s
```

**Comment by jayvdb** [comment]
Another three https://travis-ci.org/coala/docker-coala-base/builds/203114537 and https://travis-ci.org/coala/docker-coala-base/builds/203271536 and https://travis-ci.org/jayvdb/docker-coala-base/builds/203271534

**Comment by jayvdb** [comment]
And now a CheckstyleBear timeout
https://travis-ci.org/coala/docker-coala-base/builds/205108801

**Comment by jayvdb** [comment]
The CheckstyleBear timeout failures (more frequently occurring right now) are likely due to https://github.com/coala/coala-bears/issues/1084
